module.exports = {
  mode: "jit",
  purge: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      xs: { max: "539px" },
    },
    extend: {
      colors: {
        cyan: {
          "toggle-btn": "hsl(176, 100%, 44%)",
        },
        red: {
          "toggle-btn": "#D03F2F",
        },
        dark: {
          mainBg: "#434A59",
          switchBg: "#242D44",
          switchBtn: "#D03F2F",
          toggle: "#434A59",
          key: "#434A59",
          text: "#FFFFFF",
          resultBg: "#181F33",
          keypadBg: "#242D44",
          keyBg: "#EAE3DC",
          keySp: "#647198",
          keyEq: "#D03F2F",
          keyText: "#434A59",
          keyEqText: "#FFFFFF",
          hoverKeyBg: "#FFFFFE",
          hoverKeySp: "#A2B2E1",
          hoverKeyEq: "#F96B5B",
          hoverToggle: "#F96B5B",
        },
        light: {
          mainBg: "#F2F2F2;",
          switchBg: "#D2CDCD",
          switchBtn: "#C85402",
          toggle: "#D2CDCD",
          key: "#D2CDCD",
          text: "#36362C",
          resultBg: "#EEEEEE",
          keypadBg: "#D2CDCD",
          keyBg: "#E5E4E1",
          keySp: "#378187",
          keyEq: "#C85402",
          keyText: "#36362C",
          keyEqText: "#FFFFFF",
          hoverKeyBg: "#FFFFFF",
          hoverKeySp: "#62B5BC",
          hoverKeyEq: "#FF8A38",
          hoverToggle: "#FF8A38",
        },
        violet: {
          mainBg: "hsl(268, 75%, 9%)",
          switchBg: "#1E0936",
          switchBtn: "#00DED0",
          toggle: "hsl(268, 71%, 12%)",
          key: "hsl(268, 71%, 12%)",
          text: "#FFE53D",
          resultBg: "#1E0936",
          keypadBg: "#1E0936",
          keyBg: "#331C4D",
          keySp: "#56077C",
          keyEq: "#00DED0",
          keyText: "#FFE53D",
          keyEqText: "#1A2327",
          hoverKeyBg: "#6C34AC",
          hoverKeySp: "#8631AF",
          hoverKeyEq: "#93FFF8",
          hoverToggle: "#FF8A38",
        },
      },
      boxShadow: {
        darkKey: "inset 0px -4px 0px #B3A497",
        darkSpKey: "inset 0px -4px 0px #414E73",
        darkEqKey: "inset 0px -4px 0px #93261A",
        lightKey: "inset 0px -4px 0px #A79E91",
        lightSpKey: "inset 0px -4px 0px #1B6066",
        lightEqKey: "inset 0px -4px 0px #873901",
        violetKey: "inset 0px -4px 0px #881C9E",
        violetSpKey: "inset 0px -4px 0px #BE15F4",
        violetEqKey: "inset 0px -4px 0px #6CF9F1",
      },
      fontFamily: {
        spartan: ["Spartan", "sans-serif"],
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
